### ISSUE TITLE
Duplicate class okhttp3.Address

### ISSUE THREAD

**Issue by libeimarch** [hegaojian/MvvmHelper#29]
报这个错，咋整

**Comment by hegaojian** [comment]
```gradle

android {
	...
	configurations {
        all*.exclude group: 'com.squareup.okhttp3', module: 'okhttp'
    }
}

```

**Comment by hegaojian** [comment]
```gradle

android {
	...
	configurations {
        all*.exclude group: 'com.squareup.okhttp3', module: 'okhttp'
    }
}

```

**Comment by hegaojian** [comment]
试试上面这个方式

**Comment by libeimarch** [comment]
可以打包成功了，但运行报错
FATAL EXCEPTION: Anchors Thread #1
                 Process: com.ygb.driver, PID: 28608
                 java.lang.NoSuchMethodError: No static method get(Ljava/lang/String;)Lokhttp3/MediaType; in class Lokhttp3/MediaType; or its super classes (declaration of 'okhttp3.MediaType' appears in /data/app/~~egn6un_MJDhtTKxgz895GQ==/com.ygb.driver-4nFlhQ9xaQTa9wnCPgFZlw==/base.apk!classes12.dex)
                 	at rxhttp.wrapper.callback.JsonConverter.<clinit>(JsonConverter.java:13)
                 	at rxhttp.wrapper.converter.GsonConverter.create(GsonConverter.java:45)
                 	at rxhttp.wrapper.converter.GsonConverter.create(GsonConverter.java:41)
                 	at rxhttp.RxHttpPlugins.<init>(RxHttpPlugins.java:41)
                 	at rxhttp.RxHttpPlugins.<clinit>(RxHttpPlugins.java:35)
                 	at rxhttp.RxHttpPlugins.init(RxHttpPlugins.java:52)
                 	at com.ygb.driver.app.InitNetWork.run(AppTaskFactory.kt:60)
                 	at com.effective.android.anchors.Task.run(Task.kt:49)
                 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                 	at java.lang.Thread.run(Thread.java:930)
