### ISSUE TITLE
混淆后ViewBindUtilKt报错。错误信息如下。

### ISSUE THREAD

**Issue by NicodeLee** [hegaojian/MvvmHelper#47]
最近更新了Android Studio已经Gradle 到8.5。混淆打包后报下面问题。主页的混淆代码也加了
` java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
                                                                                                    	at me.hgj.mvvmhelper.ext.ViewBindUtilKt.bindingClass(ViewBindUtil.kt:49)
                                                                                                    	at me.hgj.mvvmhelper.ext.ViewBindUtilKt.inflateBinding(ViewBindUtil.kt:34)
                                                                                                    	at me.hgj.mvvmhelper.base.BaseDbFragment.initViewDataBind(BaseDbFragment.kt:27)
                                                                                                    	at me.hgj.mvvmhelper.base.BaseVmFragment.onCreateView(BaseVmFragment.kt:54)
                                                                                                    	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:3119)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:577)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:286)
                                                                                                    	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2164)
                                                                                                    	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2059)
                                                                                                    	at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1971)
                                                                                                    	at androidx.fragment.app.BackStackRecord.commitNow(BackStackRecord.java:317)
                                                                                                    	at androidx.viewpager2.adapter.FragmentStateAdapter.placeFragmentInViewHolder(FragmentStateAdapter.java:343)
                                                                                                    	at androidx.viewpager2.adapter.FragmentStateAdapter.onViewAttachedToWindow(FragmentStateAdapter.java:274)
                                                                                                    	at androidx.viewpager2.adapter.FragmentStateAdapter.onViewAttachedToWindow(FragmentStateAdapter.java:74)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView.dispatchChildAttached(RecyclerView.java:8377)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView$5.addView(RecyclerView.java:954)
                                                                                                    	at androidx.recyclerview.widget.ChildHelper.addView(ChildHelper.java:131)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView$LayoutManager.addViewInt(RecyclerView.java:9430)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:9388)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:9375)
                                                                                                    	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1676)
                                                                                                    	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1622)
                                                                                                    	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:687)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4645)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4348)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4919)
                                                                                                    	at android.view.View.layout(View.java:20686)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6202)
                                                                                                    	at androidx.viewpager2.widget.ViewPager2.onLayout(ViewPager2.java:535)
                                                                                                    	at android.view.View.layout(View.java:20686)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6202)
                                                                                                    	at androidx.appcompat.widget.LinearLayoutCompat.setChildFrame(LinearLayoutCompat.java:1665)
                                                                                                    	at androidx.appcompat.widget.LinearLayoutCompat.layoutVertical(LinearLayoutCompat.java:1519)
                                                                                                    	at androidx.appcompat.widget.LinearLayoutCompat.onLayout(LinearLayoutCompat.java:1427)
                                                                                                    	at android.view.View.layout(View.java:20686)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6202)
                                                                                                    	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                                                    	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)`

**Comment by liuya891012** [comment]
妈的，我前几天也碰到了，解决了
